# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'shockboard nice_nano_v2 nice_view'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["shockboard nice_view_adapter nice_view"]'
      modules: '["shtaiven/shockboard-zmk-config/main"]'
      custom_config: '["#define MIRYOKU_KLUDGE_MOUSEKEYSPR"]'
      branches: '["urob/zmk/main"]'
